/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package induk;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author onion
 */
public class data_perpus extends javax.swing.JFrame {
String ID = Login.getUserLogin();
private static final long serialVersionUID = 1L;
koneksi1 koneksi = new koneksi1();


   
    public data_perpus() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        tutupanggota();
        tutupbuku();
        
        

    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        petugas = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtpengembalian = new javax.swing.JLabel();
        txtpeminjaman = new javax.swing.JLabel();
        txtkunjungan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtbuku = new javax.swing.JLabel();
        txtanggota = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gambar1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nama_kelas1 = new javax.swing.JLabel();
        jumlah2 = new javax.swing.JLabel();
        jumlah = new javax.swing.JLabel();
        nama_kelas2 = new javax.swing.JLabel();
        nama_kelas3 = new javax.swing.JLabel();
        jumlah3 = new javax.swing.JLabel();
        jumlah1 = new javax.swing.JLabel();
        nama_kelas4 = new javax.swing.JLabel();
        buku7 = new javax.swing.JLabel();
        jumlah4 = new javax.swing.JLabel();
        nama_kelas5 = new javax.swing.JLabel();
        jumlah5 = new javax.swing.JLabel();
        nama_kelas = new javax.swing.JLabel();
        buku = new javax.swing.JLabel();
        total_buku7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buku1 = new javax.swing.JLabel();
        buku2 = new javax.swing.JLabel();
        buku3 = new javax.swing.JLabel();
        buku4 = new javax.swing.JLabel();
        buku5 = new javax.swing.JLabel();
        buku6 = new javax.swing.JLabel();
        total_buku = new javax.swing.JLabel();
        total_buku1 = new javax.swing.JLabel();
        total_buku2 = new javax.swing.JLabel();
        total_buku3 = new javax.swing.JLabel();
        total_buku4 = new javax.swing.JLabel();
        total_buku5 = new javax.swing.JLabel();
        total_buku6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        petugas.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        petugas.setForeground(new java.awt.Color(255, 255, 255));
        petugas.setText("0");
        petugas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        petugas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                petugasAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 310, 160, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/petugas.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data Perpustakaan SMP Pelita Atsiri");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 40));

        txtpengembalian.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        txtpengembalian.setForeground(new java.awt.Color(255, 255, 255));
        txtpengembalian.setText("0");
        txtpengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtpengembalian.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtpengembalianAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(txtpengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 310, 160, -1));

        txtpeminjaman.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        txtpeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        txtpeminjaman.setText("0");
        txtpeminjaman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtpeminjaman.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtpeminjamanAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(txtpeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 160, -1));

        txtkunjungan.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        txtkunjungan.setForeground(new java.awt.Color(255, 255, 255));
        txtkunjungan.setText("0");
        txtkunjungan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtkunjungan.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtkunjunganAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(txtkunjungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 150, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 857, -1, -1));

        txtbuku.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        txtbuku.setForeground(new java.awt.Color(255, 255, 255));
        txtbuku.setText("0");
        txtbuku.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtbuku.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtbukuAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtbukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtbukuMouseExited(evt);
            }
        });
        jPanel1.add(txtbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 160, -1));

        txtanggota.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        txtanggota.setForeground(new java.awt.Color(255, 255, 255));
        txtanggota.setText("0");
        txtanggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtanggota.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtanggotaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtanggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtanggotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtanggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtanggotaMouseExited(evt);
            }
        });
        jPanel1.add(txtanggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 160, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buku.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        gambar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/anggota1.png"))); // NOI18N
        gambar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gambar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gambar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gambar1MouseExited(evt);
            }
        });
        jPanel1.add(gambar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pengembalian.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 240, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kunjungan.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/peminjaman.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        nama_kelas1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nama_kelas1.setForeground(new java.awt.Color(255, 255, 255));
        nama_kelas1.setText("Kelas 7B : ");
        jPanel1.add(nama_kelas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        jumlah2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jumlah2.setForeground(new java.awt.Color(255, 255, 255));
        jumlah2.setText("0");
        jumlah2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jumlah2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jumlah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 70, -1));

        jumlah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jumlah.setForeground(new java.awt.Color(255, 255, 255));
        jumlah.setText("0");
        jumlah.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jumlahAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 70, -1));

        nama_kelas2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nama_kelas2.setForeground(new java.awt.Color(255, 255, 255));
        nama_kelas2.setText("Kelas 8A : ");
        jPanel1.add(nama_kelas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        nama_kelas3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nama_kelas3.setForeground(new java.awt.Color(255, 255, 255));
        nama_kelas3.setText("Kelas 8B : ");
        jPanel1.add(nama_kelas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        jumlah3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jumlah3.setForeground(new java.awt.Color(255, 255, 255));
        jumlah3.setText("0");
        jumlah3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jumlah3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jumlah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 70, -1));

        jumlah1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jumlah1.setForeground(new java.awt.Color(255, 255, 255));
        jumlah1.setText("0");
        jumlah1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jumlah1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jumlah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 70, -1));

        nama_kelas4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nama_kelas4.setForeground(new java.awt.Color(255, 255, 255));
        nama_kelas4.setText("Kelas 9A : ");
        jPanel1.add(nama_kelas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, -1));

        buku7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buku7.setForeground(new java.awt.Color(255, 255, 255));
        buku7.setText("Kategori Kamus   :");
        jPanel1.add(buku7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, -1, -1));

        jumlah4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jumlah4.setForeground(new java.awt.Color(255, 255, 255));
        jumlah4.setText("0");
        jumlah4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jumlah4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jumlah4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 70, -1));

        nama_kelas5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nama_kelas5.setForeground(new java.awt.Color(255, 255, 255));
        nama_kelas5.setText("Kelas 9B : ");
        jPanel1.add(nama_kelas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        jumlah5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jumlah5.setForeground(new java.awt.Color(255, 255, 255));
        jumlah5.setText("0");
        jumlah5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jumlah5AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jumlah5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 70, -1));

        nama_kelas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nama_kelas.setForeground(new java.awt.Color(255, 255, 255));
        nama_kelas.setText("Kelas 7A : ");
        jPanel1.add(nama_kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        buku.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buku.setForeground(new java.awt.Color(255, 255, 255));
        buku.setText("Buku Hilang         :");
        jPanel1.add(buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        total_buku7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_buku7.setForeground(new java.awt.Color(255, 255, 255));
        total_buku7.setText("0");
        total_buku7.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                total_buku7AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(total_buku7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, 70, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tmbback.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 30, -1));

        buku1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buku1.setForeground(new java.awt.Color(255, 255, 255));
        buku1.setText("Kategori IPS        :");
        jPanel1.add(buku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        buku2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buku2.setForeground(new java.awt.Color(255, 255, 255));
        buku2.setText("Kategori IPA        :");
        jPanel1.add(buku2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, -1));

        buku3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buku3.setForeground(new java.awt.Color(255, 255, 255));
        buku3.setText("Kategori MTK       :");
        jPanel1.add(buku3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        buku4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buku4.setForeground(new java.awt.Color(255, 255, 255));
        buku4.setText("Kategori Sejarah  :");
        jPanel1.add(buku4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 130, -1));

        buku5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buku5.setForeground(new java.awt.Color(255, 255, 255));
        buku5.setText("Kategori Agama   :");
        jPanel1.add(buku5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, -1, -1));

        buku6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buku6.setForeground(new java.awt.Color(255, 255, 255));
        buku6.setText("Kategori Novel     :");
        jPanel1.add(buku6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, -1, -1));

        total_buku.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_buku.setForeground(new java.awt.Color(255, 255, 255));
        total_buku.setText("0");
        total_buku.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                total_bukuAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(total_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 80, -1));

        total_buku1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_buku1.setForeground(new java.awt.Color(255, 255, 255));
        total_buku1.setText("0");
        total_buku1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                total_buku1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(total_buku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 70, -1));

        total_buku2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_buku2.setForeground(new java.awt.Color(255, 255, 255));
        total_buku2.setText("0");
        total_buku2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                total_buku2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(total_buku2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 70, -1));

        total_buku3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_buku3.setForeground(new java.awt.Color(255, 255, 255));
        total_buku3.setText("0");
        total_buku3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                total_buku3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(total_buku3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 70, -1));

        total_buku4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_buku4.setForeground(new java.awt.Color(255, 255, 255));
        total_buku4.setText("0");
        total_buku4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                total_buku4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(total_buku4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 70, -1));

        total_buku5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_buku5.setForeground(new java.awt.Color(255, 255, 255));
        total_buku5.setText("0");
        total_buku5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                total_buku5AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(total_buku5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 70, -1));

        total_buku6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_buku6.setForeground(new java.awt.Color(255, 255, 255));
        total_buku6.setText("0");
        total_buku6.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                total_buku6AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(total_buku6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, 70, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background2.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, -1, 850));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background2.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtanggotaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtanggotaAncestorAdded

        try{ 
             String sql = "select count(kd_anggota) from anggota";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
               String tampil  = res.getString("count(kd_anggota)"); 
                this.txtanggota.setText(tampil); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
   
    }//GEN-LAST:event_txtanggotaAncestorAdded

    private void txtbukuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtbukuAncestorAdded
     try{ 
             String sql = "select SUM(jumlah) from buku";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("SUM(jumlah)"); 
                this.txtbuku.setText(tampil); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
        
    }//GEN-LAST:event_txtbukuAncestorAdded

    private void txtkunjunganAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtkunjunganAncestorAdded
      try{ 
             String sql = "select count(kd_kunjungan) from kunjungan";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
               String tampil  = res.getString("count(kd_kunjungan)"); 
                this.txtkunjungan.setText(tampil); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_txtkunjunganAncestorAdded

    private void txtpeminjamanAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtpeminjamanAncestorAdded
         try{ 
             String sql = "select count(kd_peminjaman) from peminjaman";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
               String tampil  = res.getString("count(kd_peminjaman)"); 
                this.txtpeminjaman.setText(tampil); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_txtpeminjamanAncestorAdded

    private void txtpengembalianAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtpengembalianAncestorAdded
      try{ 
             String sql = "select count(kd_pengembalian) from pengembalian_dan_denda";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
               String tampil  = res.getString("count(kd_pengembalian)"); 
                this.txtpengembalian.setText(tampil); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_txtpengembalianAncestorAdded

    private void petugasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_petugasAncestorAdded
        try{ 
             String sql = "select count(id_petugas) from petugas";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("count(id_petugas)"); 
                this.petugas.setText(tampil); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_petugasAncestorAdded

    private void txtanggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtanggotaMouseClicked

    }//GEN-LAST:event_txtanggotaMouseClicked

    private void gambar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambar1MouseEntered
       anggota();
    }//GEN-LAST:event_gambar1MouseEntered

    private void gambar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambar1MouseExited
       tutupanggota();
    }//GEN-LAST:event_gambar1MouseExited

    private void jumlahAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jumlahAncestorAdded
     try{ 
             String sql = "select count(kd_anggota) from anggota where kelas = '7A' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("count(kd_anggota)"); 
                this.jumlah.setText((tampil)+ " Siswa"); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_jumlahAncestorAdded

    private void jumlah1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jumlah1AncestorAdded
        try{ 
             String sql = "select count(kd_anggota) from anggota where kelas = '7B' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("count(kd_anggota)"); 
                this.jumlah1.setText((tampil)+ " Siswa"); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_jumlah1AncestorAdded

    private void txtanggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtanggotaMouseEntered
        anggota();
    }//GEN-LAST:event_txtanggotaMouseEntered

    private void txtanggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtanggotaMouseExited
        tutupanggota();
    }//GEN-LAST:event_txtanggotaMouseExited

    private void jumlah2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jumlah2AncestorAdded
         try{ 
             String sql = "select count(kd_anggota) from anggota where kelas = '8A' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("count(kd_anggota)"); 
                this.jumlah2.setText((tampil)+ " Siswa"); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_jumlah2AncestorAdded

    private void jumlah3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jumlah3AncestorAdded
       try{ 
             String sql = "select count(kd_anggota) from anggota where kelas = '8B' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("count(kd_anggota)"); 
                this.jumlah3.setText((tampil)+ " Siswa"); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_jumlah3AncestorAdded

    private void jumlah4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jumlah4AncestorAdded
        try{ 
             String sql = "select count(kd_anggota) from anggota where kelas = '9A' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("count(kd_anggota)"); 
                this.jumlah4.setText((tampil)+ " Siswa"); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_jumlah4AncestorAdded

    private void jumlah5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jumlah5AncestorAdded
       try{ 
             String sql = "select count(kd_anggota) from anggota where kelas = '9B' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("count(kd_anggota)"); 
                this.jumlah5.setText((tampil)+ " Siswa"); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_jumlah5AncestorAdded

    private void total_buku7AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_total_buku7AncestorAdded
     try{ 
             String sql = "select sum(jumlah) from buku where kategori = 'KAMUS' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("sum(jumlah)"); 
                this.total_buku7.setText(tampil); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_total_buku7AncestorAdded

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
       buku();
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
     tutupbuku();
    }//GEN-LAST:event_jLabel5MouseExited

    private void txtbukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbukuMouseEntered
       buku();
    }//GEN-LAST:event_txtbukuMouseEntered

    private void txtbukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbukuMouseExited
    tutupbuku();
    }//GEN-LAST:event_txtbukuMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      new menu_utama_Kperpus().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void total_bukuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_total_bukuAncestorAdded
           try{ 
             String sql = "select count(kd_buku) from pengembalian_dan_denda where keterangan = 'Hilang' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("count(kd_buku)"); 
                this.total_buku.setText(tampil); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_total_bukuAncestorAdded

    private void total_buku1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_total_buku1AncestorAdded
          try{ 
             String sql = "select sum(jumlah) from buku where kategori = 'IPS' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("sum(jumlah)"); 
                this.total_buku1.setText(tampil); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_total_buku1AncestorAdded

    private void total_buku2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_total_buku2AncestorAdded
        try{ 
             String sql = "select sum(jumlah) from buku where kategori = 'IPA' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("sum(jumlah)"); 
                this.total_buku2.setText(tampil); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_total_buku2AncestorAdded

    private void total_buku3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_total_buku3AncestorAdded
       try{ 
             String sql = "select sum(jumlah) from buku where kategori = 'MATEMATIKA' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("sum(jumlah)"); 
                this.total_buku3.setText(tampil); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_total_buku3AncestorAdded

    private void total_buku4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_total_buku4AncestorAdded
       try{ 
             String sql = "select sum(jumlah) from buku where kategori = 'SEJARAH' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("sum(jumlah)"); 
                this.total_buku4.setText(tampil); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_total_buku4AncestorAdded

    private void total_buku5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_total_buku5AncestorAdded
        try{ 
             String sql = "select sum(jumlah) from buku where kategori = 'AGAMA' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("sum(jumlah)"); 
                this.total_buku5.setText(tampil); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_total_buku5AncestorAdded

    private void total_buku6AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_total_buku6AncestorAdded
      try{ 
             String sql = "select sum(jumlah) from buku where kategori = 'NOVEL' ";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                String tampil  = res.getString("sum(jumlah)"); 
                this.total_buku6.setText(tampil); 
            }
        }catch (Exception e){ 
            System.err.println(e); 
        }
    }//GEN-LAST:event_total_buku6AncestorAdded

    
    private void buku(){
    buku.setVisible(true); 
    buku1.setVisible(true);
    buku2.setVisible(true);
    buku3.setVisible(true);
    buku4.setVisible(true);
    buku5.setVisible(true);
    buku6.setVisible(true);
    buku7.setVisible(true);
    total_buku.setVisible(true);
    total_buku1.setVisible(true);
    total_buku2.setVisible(true);
    total_buku3.setVisible(true);
    total_buku4.setVisible(true);
    total_buku5.setVisible(true);
    total_buku6.setVisible(true);
    total_buku7.setVisible(true);
    }
    
    private void tutupbuku(){  
    buku.setVisible(false); 
    buku1.setVisible(false);
    buku2.setVisible(false);
    buku3.setVisible(false);
    buku4.setVisible(false);
    buku5.setVisible(false);
    buku6.setVisible(false);
    buku7.setVisible(false);
    total_buku.setVisible(false);
    total_buku1.setVisible(false);
    total_buku2.setVisible(false);
    total_buku3.setVisible(false);
    total_buku4.setVisible(false);
    total_buku5.setVisible(false);
    total_buku6.setVisible(false);
    total_buku7.setVisible(false);
    }
    
    
    private void anggota(){
    nama_kelas.setVisible(true);
    jumlah.setVisible(true);
    nama_kelas1.setVisible(true);
    jumlah1.setVisible(true);
    nama_kelas2.setVisible(true);
    jumlah2.setVisible(true);
    nama_kelas3.setVisible(true);
    jumlah3.setVisible(true);
    nama_kelas4.setVisible(true);
    jumlah4.setVisible(true);
    nama_kelas5.setVisible(true);
    jumlah5.setVisible(true);
}
    
    private void tutupanggota(){
    nama_kelas.setVisible(false);
    jumlah.setVisible(false);
    nama_kelas1.setVisible(false);
    jumlah1.setVisible(false);
    nama_kelas2.setVisible(false);
    jumlah2.setVisible(false);
    nama_kelas3.setVisible(false);
    jumlah3.setVisible(false);
    nama_kelas4.setVisible(false);
    jumlah4.setVisible(false);
    nama_kelas5.setVisible(false);
    jumlah5.setVisible(false);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_perpus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buku;
    private javax.swing.JLabel buku1;
    private javax.swing.JLabel buku2;
    private javax.swing.JLabel buku3;
    private javax.swing.JLabel buku4;
    private javax.swing.JLabel buku5;
    private javax.swing.JLabel buku6;
    private javax.swing.JLabel buku7;
    private javax.swing.JLabel gambar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel jumlah1;
    private javax.swing.JLabel jumlah2;
    private javax.swing.JLabel jumlah3;
    private javax.swing.JLabel jumlah4;
    private javax.swing.JLabel jumlah5;
    private javax.swing.JLabel nama_kelas;
    private javax.swing.JLabel nama_kelas1;
    private javax.swing.JLabel nama_kelas2;
    private javax.swing.JLabel nama_kelas3;
    private javax.swing.JLabel nama_kelas4;
    private javax.swing.JLabel nama_kelas5;
    private javax.swing.JLabel petugas;
    private javax.swing.JLabel total_buku;
    private javax.swing.JLabel total_buku1;
    private javax.swing.JLabel total_buku2;
    private javax.swing.JLabel total_buku3;
    private javax.swing.JLabel total_buku4;
    private javax.swing.JLabel total_buku5;
    private javax.swing.JLabel total_buku6;
    private javax.swing.JLabel total_buku7;
    private javax.swing.JLabel txtanggota;
    private javax.swing.JLabel txtbuku;
    private javax.swing.JLabel txtkunjungan;
    private javax.swing.JLabel txtpeminjaman;
    private javax.swing.JLabel txtpengembalian;
    // End of variables declaration//GEN-END:variables
}
